---
title: "Recitation 02"
author: "Beau Meche"
date: "9/12/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r toolbox}

# request census API key: https://api.census.gov/data/key_signup.html
# this takes time to load / register

library(usethis)

edit_r_environ()

library(tidycensus)

library(tidyverse)

library(ggplot2)

```

```{r}

pop <- get_decennial(geography = "state",
                     variables = c("P001001", "P002005"),
                     year = 2010,
                     output = "wide")

glimpse(pop)


# length(unique(pop$NAME))
# ifelse(length(unique(pop$NAME)) == 52, T, F)

rural <- pop %>% 
  rename(state = NAME) %>% 
  mutate(prop_rural = (P002005/P001001),
         state = reorder(state, prop_rural))

# glimpse(rural)

rural %>%
  ggplot(aes(x = prop_rural, y = state)) +
  geom_point() +
  ylab("") +
  xlab("Rural Population Proportion")


```

```{r make_map, cache=T}

rural01 <- get_decennial(geography = "state",
                     variables = c("P001001", "P002005"),
                     year = 2010,
                     output = "wide",
                     geometry = T) %>% 
       rename(state = NAME) %>% 
       mutate(prop_rural = (P002005/P001001),
              state = reorder(state, prop_rural))
        
# glimpse(rural01)

# step 01 -- Q: how can we make this a bit more informative? what do you think
# the cause of this viewpoint is? 

rural01 %>% 
  ggplot() +
  geom_sf()

# step 02 -- zoom in

rural01 %>%
  filter(! state %in% c("Alaska", "Hawaii", "Puerto Rico")) %>%
  ggplot(aes(fill = prop_rural)) +
  geom_sf() +
  labs(
    title = "Congratulations, Your first map!",
    caption = "Always cite your data: US Census Bureau"
  )

# step 3
# A great function for providing the fill colors for maps 
# is scale_fill_viridis_c()

rural01 %>%
  filter(! state %in% c("Alaska", "Hawaii", "Puerto Rico")) %>%
  ggplot(aes(fill = prop_rural*100)) +
  geom_sf() +
  scale_fill_viridis_c(option = "plasma",
                     direction = -1) +
  labs(
    title = "Congratulations, Your first map!",
    caption = "Always cite your data: US Census Bureau 2010",
    fill = "% Rural"
  ) +
  theme_dark()

# step 4: Alaska + Hawaii
# remove filter and add shift arg. 

rural02 <- get_decennial(geography = "state",
                     variables = c("P001001", "P002005"),
                     year = 2010,
                     output = "wide",
                     geometry = T, 
                     shift_geo = T) %>% 
       rename(state = NAME) %>% 
       mutate(prop_rural = (P002005/P001001),
              state = reorder(state, prop_rural))

rural02 %>%
  # filter(! state %in% c("Alaska", "Hawaii", "Puerto Rico")) %>%
  ggplot(aes(fill = prop_rural*100)) +
  geom_sf() +
  scale_fill_viridis_c(option = "plasma",
                     direction = -1) +
  labs(
    title = "Congratulations, Your first map!",
    caption = "Always cite your data: US Census Bureau 2010",
    fill = "% Rural"
  ) +
  theme_dark()



```

```{r county_map, cache = T}

# cheat sheet for race vars in census data

races <- c(White = "B02001_002", 
           Black = "B02001_003", 
           Asian = "B02001_005",
           Hispanic = "B03003_003")

# I live here:

laffy <- get_acs(geography = "tract",
                 variables = races, 
                 year = 2018,
                 state = "OK",
                 county = "Oklahoma County",
                 geometry = TRUE,
                 
                 # the total population
                 
                 summary_var = "B02001_001") 

glimpse(laffy)

laffy %>%
  mutate(Percent = 100 * (estimate / summary_est)) %>%
  ggplot(aes(fill = Percent, color = Percent)) +
  facet_wrap(~ variable) +
  geom_sf() +
  scale_fill_viridis_c(direction = -1) +
  scale_color_viridis_c(direction = -1) +
  labs(title = "Racial geography of Lafayette Parish, LA",
       caption = "Source: American Community Survey 2014-2018") +
  theme_void()

```




